# Generated by Django 5.2.6 on 2025-10-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.FileField(upload_to='media\\img\\card'),
        ),
    ]
