# Generated by Django 5.2.6 on 2025-10-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_game_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='link',
            field=models.CharField(max_length=255, verbose_name='Якорь'),
        ),
    ]
