# Generated by Django 5.2.6 on 2025-10-06 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_game_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='title',
            new_name='name',
        ),
    ]
